<a href="https://colab.research.google.com/github/cristian-rincon/escuela-datascience/blob/master/manipulacion_datos_pandas/1_pandas_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

list_1 = [1,2,3,4,5]

list_2 = np.array(list_1) + 10 # this will add 10 to every number into the array
list_2

array([11, 12, 13, 14, 15])

## Getting information about how many elements are into np array

In [ ]:
list_3 = np.array(list_2).shape
list_3

(5,)

## Creating matrix

In [ ]:
sample_matrix = np.array([list_1,list_2])
sample_matrix

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [ ]:
sample_matrix.shape

(2, 5)

## Access to element into matrix

In [ ]:
sample_matrix[0][1]

2

## Pandas Series

In [ ]:
import pandas as pd

In [ ]:
pd.Series([10,9,8,7,6])

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [ ]:
serie_1 = pd.Series([10,9,8,7,6])
serie_1.values

array([10,  9,  8,  7,  6])

In [ ]:
serie_1.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
serie_1.shape

(5,)

In [ ]:
serie_1[3]

7

### Custom index

In [ ]:
sr_1 = pd.Series([10,9,8,7,6], index=['a','b','c','d','e'])
sr_1

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [ ]:
sr_1['b':'e']

b    9
c    8
d    7
e    6
dtype: int64

## Dictionary

In [ ]:
dict_data = {'CO':100,
            'MX':200,
            'AR':300}
dict_data

{'AR': 300, 'CO': 100, 'MX': 200}

In [ ]:
dict_data.keys()

dict_keys(['CO', 'MX', 'AR'])

In [ ]:
dict_data['CO']

100

## Convert data from dict to Pandas Series

In [ ]:
sr_2 = pd.Series(dict_data, index=['CO','MX','PE']) # If not a index, pandas will fill it with NaN
sr_2

CO    100.0
MX    200.0
PE      NaN
dtype: float64

### Get True if value is NULL 

In [ ]:
sr_2.isnull()

CO    False
MX    False
PE     True
dtype: bool

### Get True if value is not NULL

In [ ]:
sr_2.notnull()

CO     True
MX     True
PE    False
dtype: bool