<a href="https://colab.research.google.com/github/cristian-rincon/escuela-datascience/blob/master/manipulacion_datos_pandas/8_concat_append.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.0.5'

In [2]:
pd.options.display.float_format='{:.2f}'.format

In [10]:
np.set_printoptions(precision=1)

In [12]:
x1 = np.random.rand(2,5)*10
x1

array([[6.3, 5.6, 5.8, 4.6, 3.7],
       [8.3, 9.3, 6.4, 6.8, 3.3]])

In [7]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.13, -0.83, -0.42, -0.06, -0.27],
       [-0.08, -0.62, -0.16, -0.18, -0.9 ]])

## Concatenación Vertical

In [14]:
obj1 = np.concatenate([x1,x2])
obj1

array([[ 6.3,  5.6,  5.8,  4.6,  3.7],
       [ 8.3,  9.3,  6.4,  6.8,  3.3],
       [-0.1, -0.8, -0.4, -0.1, -0.3],
       [-0.1, -0.6, -0.2, -0.2, -0.9]])

In [15]:
obj1.shape

(4, 5)

## Concatenación Horizontal

In [18]:
np.concatenate([x1,x2],axis=1)

array([[ 6.3,  5.6,  5.8,  4.6,  3.7, -0.1, -0.8, -0.4, -0.1, -0.3],
       [ 8.3,  9.3,  6.4,  6.8,  3.3, -0.1, -0.6, -0.2, -0.2, -0.9]])

## Ahora con Pandas

In [19]:
s1 = pd.Series(x1[0],index=['a','b','c','d','e'])
s1

a   6.28
b   5.58
c   5.81
d   4.56
e   3.72
dtype: float64

In [20]:
s2 = pd.Series(x1[0],index=['c','d','e','f','g'])
s2

c   6.28
d   5.58
e   5.81
f   4.56
g   3.72
dtype: float64

In [22]:
pd.concat([s1,s2], axis=1)

0    1
a 6.28  nan
b 5.58  nan
c 5.81 6.28
d 4.56 5.58
e 3.72 5.81
f  nan 4.56
g  nan 3.72

In [23]:
s1.reset_index(drop=True)

0   6.28
1   5.58
2   5.81
3   4.56
4   3.72
dtype: float64

In [24]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0    1
0 6.28 6.28
1 5.58 5.58
2 5.81 5.81
3 4.56 4.56
4 3.72 3.72

In [30]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 9.46 6.46
1 2.62 2.94
2 1.10 0.76

In [29]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index=[2,3,4])
df2

a     b
2 -0.17 -0.33
3 -0.23 -0.24
4 -0.72 -0.14

In [31]:
pd.concat([df1,df2])

a     b
0  9.46  6.46
1  2.62  2.94
2  1.10  0.76
2 -0.17 -0.33
3 -0.23 -0.24
4 -0.72 -0.14

In [32]:
pd.concat([df1,df2],axis=1)

a    b     a     b
0 9.46 6.46   nan   nan
1 2.62 2.94   nan   nan
2 1.10 0.76 -0.17 -0.33
3  nan  nan -0.23 -0.24
4  nan  nan -0.72 -0.14

In [33]:
pd.concat([df1,df2],axis=1,join='inner')

a    b     a     b
2 1.10 0.76 -0.17 -0.33

In [34]:
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 9.46 6.46 -0.17 -0.33
1 2.62 2.94 -0.23 -0.24
2 1.10 0.76 -0.72 -0.14

## Usando Append

In [35]:
df1.append(df2)

a     b
0  9.46  6.46
1  2.62  2.94
2  1.10  0.76
2 -0.17 -0.33
3 -0.23 -0.24
4 -0.72 -0.14

In [36]:
df1.T

0    1    2
a 9.46 2.62 1.10
b 6.46 2.94 0.76

In [38]:
df1.T.append(df2.T).T

a    b     a     b
0 9.46 6.46   nan   nan
1 2.62 2.94   nan   nan
2 1.10 0.76 -0.17 -0.33
3  nan  nan -0.23 -0.24
4  nan  nan -0.72 -0.14